"""Initial migration

Revision ID: 26a46714073c
Revises: 
Create Date: 2024-07-25 09:33:28.435715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26a46714073c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredient')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('sugas', sa.NUMERIC(), nullable=False),
    sa.Column('fats', sa.NUMERIC(), nullable=False),
    sa.Column('slng', sa.NUMERIC(), nullable=False),
    sa.Column('other_solids', sa.NUMERIC(), nullable=False),
    sa.Column('total_solid', sa.NUMERIC(), nullable=False),
    sa.Column('pod', sa.NUMERIC(), nullable=False),
    sa.Column('pac', sa.NUMERIC(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
